spring.application.name=assignment
server.shutdown=graceful

spring.threads.virtual.enabled=true

openai.api.key=${OPENAI_API_KEY:}
openai.api.base-url=https://api.openai.com
openai.model=gpt-4o-mini-transcribe